name: Glossary
on:
  push:
    branches:
      - main # Set a branch name to trigger deployment
  pull_request:
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    env:
      DTC_HEADLES: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: 'true'
      - name: Setup docToolchain
        run: chmod +x dtcw
      - name: Change permissions
        run: chmod -R 777 .
      - name: list
        run: find . -type f
      - name: run dtcw
        run: ./dtcw tasks
      - name: Migrate Markdown based ADRs from adr-tools to AsciiDoc
        run: ./dtcw --debug --stacktrace --info exportMarkdown 
      - name: Copy documentation structure
        run: cp -r ./build/Documentation_structure ./GitHub_Pages/
      - name: Create glossary.adoc
        run: chmod +x ./generate_includes.sh; ./generate_includes.sh
      - name: Update images
        run: chmod +x ./image_preprocess.sh; ./image_preprocess.sh
      - name: Generate PDF
        run: ./dtcw generatePDF  
      - name: Archive pdf artifacts
        uses: actions/upload-artifact@v4.3.4
        with:
          name: pdf-output
          path: build/pdf/internet-banking-system.pdf
          retention-days: 90
  deploy:    # Add a dependency to the build job
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: pdf-output
      url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action  uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: github-pages # optional, default is github-pages
